### ISSUE TITLE
Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/316581/en.xml

### ISSUE THREAD

**Issue by overdox** [SickRage/SickRage#2686]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master
OS: Linux Debian 8
What you did:Update show
What happened:sickrage failed to retrive show update
What you expected:updated show information from tvdb
Logs:
AA raise tvdb_error(e)
AA File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
AA self.config['url_seriesInfo'] % (sid, getShowInLanguage)
AA File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
AA myShow = t[ep_obj.show.indexerid]
AA File "/opt/sickrage/sickbeard/metadata/kodi_12plus.py", line 256, in _ep_data
AATraceback (most recent call last):
2016-12-10 02:08:34 INFO SHOWUPDATER :: Could not get the recently updated show data from theTVDB. Retrying later. Url was: http://thetvdb.com/api/Updates.php?type=series&time=1481245401
2016-12-10 02:08:34 INFO SHOWUPDATER :: Request failed: 403 Client Error: Forbidden for url: http://thetvdb.com/api/Updates.php?type=series&time=1481245401
2016-12-08 02:26:05 INFO SHOWUPDATER :: Could not get the recently updated show data from theTVDB. Retrying later. Url was: http://thetvdb.com/api/Updates.php?type=series&time=1481073917
2016-12-08 02:26:05 INFO SHOWUPDATER :: Request failed: HTTPConnectionPool(host='thetvdb.com', port=80): Read timed out. (read timeout=30)

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!
