### ISSUE TITLE
Show Marvel's Guardians of the Galaxy are not found on ethor tracker

### ISSUE THREAD

**Issue by thenamelessthing** [SickRage/SickRage#3150]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Ubuntu 14.04
What you did: I added Marvel's Guardians of the Galaxy and try to snatched it from Ethor tracker (with jackett)
What happened: I think it search with it's french name but on the tracker the name are in english. On tvdb the name seem to be in english.
What you expected: Try to search the name with both english and french name
Logs:

2017-02-14 18:48:26 INFO SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: Performing season pack search for Les gardiens de la galaxie
2017-02-14 18:48:26 DEBUG SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: Fallback season pack search initiate
2017-02-14 18:48:26 DEBUG SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: GET URL: http://nxworld.club:9117/torznab/ethor/api?apikey=**********&maxage=500&cat=5000%2C5010%2C5020%2C5030%2C5040%2C5050%2C5070&q=Les+gardiens+de+la+galaxie+S01E22&limit=100&t=search&offset=0 [Status: 200]
2017-02-14 18:48:24 DEBUG SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: Search string: Les gardiens de la galaxie S01E22
2017-02-14 18:48:24 DEBUG SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: Search Mode: Episode
2017-02-14 18:48:24 DEBUG SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: GET URL: http://nxworld.club:9117/torznab/ethor/api?apikey=**********&t=caps [Status: 200]
2017-02-14 18:48:23 INFO SEARCHQUEUE-MANUAL-293614 :: [Ethor] :: Performing episode search for Les gardiens de la galaxie
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by sharkykh** [comment]
I don't think it's actually a bug, but maybe you can override it:
Edit the show in SickRage, on Advanced tab, add the show's english title a Scene Exception name and save.
Force a search again.

**Comment by thenamelessthing** [comment]
@sharkykh It work with your tips!  Thanks you.  Can you explain why he doesn't also try with the english title?

**Comment by miigotu** [comment]
You have it added in SR with the french title. Unless there is a scene exception added it uses just the main title to search with.  That scene exception can be a user entered one like you just did, or added to the master scene exceptions list on https://github.com/SickRage/sickrage.github.io/blob/master/scene_exceptions/scene_exceptions.json

**Comment by romanocry** [comment]
Just to know, Marvel's Gadian of Galaxie is juste a movie, no ? Not a show ...

**Comment by thenamelessthing** [comment]
@romanocry it's even a cartoon!

**Comment by forkless** [comment]
It's not a SR issue, the release group added the episode name of s03e01 to the title of the show in their releases, hence it can not find anything. Try adding **Marvels.Guardians.of.the.Galaxy.Mission.Breakout** as a scene exception for season 03.

**Comment by miigotu** [comment]
Way to resurrect a 14 month old issue lol.
